name: Build and Push Docker Image

on:
  push:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: Checkout 代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 步骤 3: 登录到 GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 步骤 4: 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/cli-test:${{ github.sha }} .

      # 步骤 5: 推送 Docker 镜像到 GitHub Container Registry
      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}/cli-test:${{ github.sha }}

