name: Build nRF Connect SDK Coprocessor Example

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NRF_SDK_VERSION: v3.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake gcc-arm-none-eabi


      - name: Setup 
        run: |
          git clone --recursive https://github.com/openthread/ot-nrf528xx.git
          cd ot-nrf528xx
          git submodule update --init
          ./script/bootstrap
          echo ls
          ./script/build nrf52840 USB_trans -DOT_BOOTLOADER=USB
          ls
          pwd
          cd build
          ls
          cd output
          ls

   
      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output/nrf52840/bin/ot-rcp.hex
