name: Github Actions Demo
on:
  push:
    branches:
      - main
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, World!"
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: '1.20'
        run: go version