name: Github Actions Demo
on:
  push:
    branches:
      - main
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, World!"
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: '1.20'
      - run: go version
      - name: Install dependencies
        run: |
          go mod download
      - name: Build Go project
        run: |
          go build -o myapp .
      - name: Run myapp
        run: |
          ./myapp
      - name: Set execute permissions for snb
        run: chmod +x ./snb
      - name: Sign firmware
        run: |
          echo "Sign firmware..."
          ./snb kms sign -k 01 -a hmac -f ./myapp -o signed_firmware.bin
      - name: Upload build artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: ./myapp
      - name: Get artifact download URL
        run: |
            DOWNLOAD_URL="${{ steps.upload_artifact.outputs.artifact-url }}"
            echo "Artifact download URL: $DOWNLOAD_URL"